version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: ./Dockerfile
    env_file:
    - .env
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
      - "9876:9876"
    user: "1000"
  server:
    build:
      context: ./docker/server
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    user: "1000"
